export type Product = {
  id: number;
  name: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  image: string;
  category: string;
  badge?: "sale" | "featured" | "new";
  description: string;
};

export const categories = ["All", "Electronics", "Clothing", "Home & Living", "Sports", "Beauty"];

export const products: Product[] = [
  {
    id: 1,
    name: "Wireless Noise-Cancelling Headphones",
    price: 79.99,
    originalPrice: 129.99,
    rating: 4.8,
    reviewCount: 2341,
    image: "https://cdn.thewirecutter.com/wp-content/media/2023/09/noise-cancelling-headphone-2048px-0876.jpg?width=2048&quality=60&crop=2048:1365&auto=webp",
    category: "Electronics",
    badge: "sale",
    description: "Premium sound with active noise cancellation and 30-hour battery life.",
  },
  {
    id: 2,
    name: "Minimalist Leather Watch",
    price: 149.99,
    rating: 4.7,
    reviewCount: 876,
    image: "https://www.peugeotwatches.com/cdn/shop/products/2059G-FV.jpg?v=1633106380&width=1500",
    category: "Clothing",
    badge: "featured",
    description: "Slim profile with genuine leather strap and sapphire crystal glass.",
  },
  {
    id: 3,
    name: "Smart Fitness Tracker",
    price: 59.99,
    originalPrice: 89.99,
    rating: 4.5,
    reviewCount: 1543,
    image: "https://cdn.thewirecutter.com/wp-content/media/2023/06/fitnesstrackers-2048px-09819-2x1-1.jpg?width=2048&quality=75&crop=2:1&auto=webp",
    category: "Sports",
    badge: "sale",
    description: "Track steps, heart rate, sleep, and more with a 7-day battery.",
  },
  {
    id: 4,
    name: "Ceramic Pour-Over Coffee Set",
    price: 44.99,
    rating: 4.9,
    reviewCount: 412,
    image: "https://m.media-amazon.com/images/I/7159+ELcEOL._AC_UF894,1000_QL80_.jpg",
    category: "Home & Living",
    badge: "new",
    description: "Handcrafted ceramic dripper with matching carafe for the perfect brew.",
  },
  {
    id: 5,
    name: "Organic Face Serum",
    price: 34.99,
    originalPrice: 49.99,
    rating: 4.6,
    reviewCount: 987,
    image: "https://activeearth.com/cdn/shop/files/organic_face_serum.jpg?v=1741224076&width=1500",
    category: "Beauty",
    badge: "sale",
    description: "Vitamin C & hyaluronic acid blend for radiant, hydrated skin.",
  },
  {
    id: 6,
    name: "Ultralight Running Shoes",
    price: 119.99,
    rating: 4.7,
    reviewCount: 2109,
    image: "https://cdn.runrepeat.com/storage/gallery/buying_guide_primary/64/best-lightweight-running-shoes-001-22300149-main.jpg",
    category: "Sports",
    badge: "featured",
    description: "Responsive foam cushioning with breathable mesh upper for long runs.",
  },
  {
    id: 7,
    name: "Portable Bluetooth Speaker",
    price: 49.99,
    originalPrice: 69.99,
    rating: 4.4,
    reviewCount: 1876,
    image: "https://cdn.thewirecutter.com/wp-content/media/2024/11/portablebluetoothspeakers-2048px-9130.jpg?width=2048&quality=60&crop=2048:1365&auto=webp",
    category: "Electronics",
    badge: "sale",
    description: "360° sound with waterproof design and 12-hour playtime.",
  },
  {
    id: 8,
    name: "Linen Button-Down Shirt",
    price: 54.99,
    rating: 4.5,
    reviewCount: 634,
    image: "https://www.billyreid.com/cdn/shop/files/s24_102-1508_tuscumbia-linen-shirt-button-down_white_44.jpg?v=1773174568&width=700",
    category: "Clothing",
    badge: "new",
    description: "Breathable 100% linen in a relaxed fit, perfect for warm days.",
  },
  {
    id: 9,
    name: "Bamboo Desk Organizer",
    price: 29.99,
    rating: 4.6,
    reviewCount: 321,
    image: "https://meedenart.com/cdn/shop/files/1-07_a24e45f6-ae9b-4b15-b218-cc80ca127696_1600x.png?v=1732685200",
    category: "Home & Living",
    description: "Sustainable bamboo with 6 compartments to keep your workspace tidy.",
  },
  {
    id: 10,
    name: "Retinol Night Cream",
    price: 39.99,
    originalPrice: 55.99,
    rating: 4.8,
    reviewCount: 1102,
    image: "https://i5.walmartimages.com/seo/Equate-Beauty-Retinol-Night-Cream-1-7-oz_8785c3d1-c322-4562-a57b-1bd5ae468831.e1baa221f7c55d345a5c6cb858f93532.jpeg",
    category: "Beauty",
    badge: "sale",
    description: "Clinically proven retinol formula to reduce fine lines overnight.",
  },
  {
    id: 11,
    name: "Mechanical Keyboard",
    price: 89.99,
    rating: 4.7,
    reviewCount: 3201,
    image: "https://cdn.thewirecutter.com/wp-content/media/2025/12/BEST-MECHANICAL-KEYBOARDS-2048px-EVOWORKS-80-926.jpg?width=2048&quality=60&crop=2048:1365&auto=webp",
    category: "Electronics",
    badge: "featured",
    description: "Tactile brown switches with RGB backlighting and aluminum frame.",
  },
  {
    id: 12,
    name: "Yoga Mat Pro",
    price: 64.99,
    originalPrice: 84.99,
    rating: 4.9,
    reviewCount: 789,
    image: "https://www.manduka.com/cdn/shop/files/111011050-Mats-PRO71-BLACK-SAGE-01.jpg?v=1768944270&width=871",
    category: "Sports",
    badge: "sale",
    description: "6mm thick non-slip surface with alignment lines and carry strap.",
  },
];
